"""
Django settings for kcalibra project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _cargar_dotenv(ruta):
    """
    Lee un fichero .env y mete sus variables en el entorno del proceso (os.environ), a mano,
    sin ninguna librería externa. ¿Por qué a mano? Porque esta unidad solo tiene autorizadas
    tres dependencias nuevas (Django, el conector de PostgreSQL y django-template-partials);
    una cuarta solo para esto (la típica sería `python-dotenv`) no compensa: el formato es
    trivial y son diez líneas de código, no una dependencia más que mantener.

    Formato: una variable por línea, "NOMBRE=valor". Las líneas vacías o que empiezan por "#"
    se ignoran. Si una variable YA existe en el entorno (por ejemplo, puesta a mano en la
    terminal, o por systemd en un futuro servidor), esa variable externa manda y no se pisa:
    así el mismo mecanismo sirve en local y en un despliegue real.
    """
    if not ruta.exists():
        # Sin .env no pasa nada aquí todavía: las variables obligatorias se exigen más abajo,
        # una a una, con un mensaje que dice cuál falta (ver `variable_obligatoria`).
        return
    for linea in ruta.read_text(encoding="utf-8").splitlines():
        linea = linea.strip()
        if not linea or linea.startswith("#") or "=" not in linea:
            continue
        clave, _, valor = linea.partition("=")
        os.environ.setdefault(clave.strip(), valor.strip())


_cargar_dotenv(BASE_DIR / ".env")


def variable_obligatoria(nombre):
    """
    Lee una variable de entorno que la aplicación necesita para arrancar (la clave secreta,
    los datos de conexión a la base...). Si falta, para el arranque aquí mismo con un mensaje
    que dice exactamente qué falta (criterio R7), en vez de dos alternativas peores:
    seguir con un valor por defecto inseguro, o dejar que reviente más adelante con un error
    críptico (por ejemplo, psycopg quejándose de que no encuentra un host que nunca se le dio).
    """
    valor = os.environ.get(nombre)
    if not valor:
        raise ImproperlyConfigured(
            f"Falta la variable de entorno obligatoria '{nombre}'. "
            "Copia .env.example a .env, rellénalo, y vuelve a intentarlo. "
            "Instrucciones completas en AGENTS.md."
        )
    return valor


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = variable_obligatoria("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto False (el valor seguro): si alguien se olvida de poner DJANGO_DEBUG en el
# entorno de un servidor real, que falle "hacia lo seguro" y no al revés.
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Terceros: da soporte a {% partialdef %} en las plantillas (ver R4). Django 5.2 no lo
    # trae de serie (llegará en la 6.0); sin él, las plantillas se enredan en cuanto entra
    # HTMX, que necesita devolver "trozos" de página sueltos.
    "template_partials",
    "paginas",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "kcalibra.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Plantillas compartidas entre apps (la base con Tailwind, HTMX y Alpine ya cargados)
        # viven aquí, no dentro de una app concreta.
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kcalibra.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": variable_obligatoria("DB_NAME"),
        "USER": variable_obligatoria("DB_USER"),
        "PASSWORD": variable_obligatoria("DB_PASSWORD"),
        "HOST": variable_obligatoria("DB_HOST"),
        "PORT": variable_obligatoria("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Aquí viven los ficheros estáticos que no pertenecen a ninguna app concreta: el CSS que
# genera el binario de Tailwind, y las copias locales de HTMX y Alpine (R3, R5, "Cómo" punto 6).
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
