"""
Django settings for kcalibra project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _cargar_dotenv(ruta):
    """
    Lee un fichero .env y mete sus variables en el entorno del proceso (os.environ), a mano,
    sin ninguna librería externa. ¿Por qué a mano? Porque esta unidad solo tiene autorizadas
    tres dependencias nuevas (Django, el conector de PostgreSQL y django-template-partials);
    una cuarta solo para esto (la típica sería `python-dotenv`) no compensa: el formato es
    trivial y son diez líneas de código, no una dependencia más que mantener.

    Formato: una variable por línea, "NOMBRE=valor". Las líneas vacías o que empiezan por "#"
    se ignoran. Si una variable YA existe en el entorno (por ejemplo, puesta a mano en la
    terminal, o por systemd en un futuro servidor), esa variable externa manda y no se pisa:
    así el mismo mecanismo sirve en local y en un despliegue real.
    """
    if not ruta.exists():
        # Sin .env no pasa nada aquí todavía: las variables obligatorias se exigen más abajo,
        # una a una, con un mensaje que dice cuál falta (ver `variable_obligatoria`).
        return
    for linea in ruta.read_text(encoding="utf-8").splitlines():
        linea = linea.strip()
        if not linea or linea.startswith("#") or "=" not in linea:
            continue
        clave, _, valor = linea.partition("=")
        os.environ.setdefault(clave.strip(), valor.strip())


_cargar_dotenv(BASE_DIR / ".env")


def variable_obligatoria(nombre):
    """
    Lee una variable de entorno que la aplicación necesita para arrancar (la clave secreta,
    los datos de conexión a la base...). Si falta, para el arranque aquí mismo con un mensaje
    que dice exactamente qué falta (criterio R7), en vez de dos alternativas peores:
    seguir con un valor por defecto inseguro, o dejar que reviente más adelante con un error
    críptico (por ejemplo, psycopg quejándose de que no encuentra un host que nunca se le dio).
    """
    valor = os.environ.get(nombre)
    if not valor:
        raise ImproperlyConfigured(
            f"Falta la variable de entorno obligatoria '{nombre}'. "
            "Copia .env.example a .env, rellénalo, y vuelve a intentarlo. "
            "Instrucciones completas en AGENTS.md."
        )
    return valor


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = variable_obligatoria("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto False (el valor seguro): si alguien se olvida de poner DJANGO_DEBUG en el
# entorno de un servidor real, que falle "hacia lo seguro" y no al revés.
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # `django.contrib.sites` y las apps de allauth: la unidad 003 monta el alta, la entrada
    # y la salida sobre `django-allauth` en vez de vistas hechas a mano (decisión del curso,
    # ver docs/decisiones del meta-repo). `sites` es una dependencia dura de allauth aunque
    # esta app solo tenga un sitio: allauth lo usa para construir enlaces absolutos en los
    # correos (por eso hace falta SITE_ID más abajo).
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    # Terceros: da soporte a {% partialdef %} en las plantillas (ver R4). Django 5.2 no lo
    # trae de serie (llegará en la 6.0); sin él, las plantillas se enredan en cuanto entra
    # HTMX, que necesita devolver "trozos" de página sueltos.
    "template_partials",
    "paginas",
    # cuentas: quién eres y cómo entras. hogares: con quién compartes y quién ve qué.
    # Unidad 003 — ver docs/05-trabajo/003-cuentas-y-hogares/especificacion.md del meta-repo.
    "cuentas",
    "hogares",
    # perfiles: los datos físicos, el objetivo y las manías de cada persona, y las calorías
    # y macros que salen de ellos. Unidad 004 — ver
    # docs/05-trabajo/004-perfil-y-objetivo-del-dia/especificacion.md del meta-repo. La
    # fórmula en sí NO vive aquí (R8): vive en `servicios/`, que esta unidad estrena.
    "perfiles",
    # planes: el plan de comidas del día, apuntado a mano, y el Inicio de verdad. Unidad 005
    # — ver docs/05-trabajo/005-plan-a-mano-e-inicio/especificacion.md del meta-repo. Es DEL
    # HOGAR (G-43, a diferencia de perfiles): el primer modelo de negocio que cuelga de
    # `hogares.ModeloDeHogar` (unidad 003).
    "planes",
    # progreso: la evolución de peso, grasa y cintura de cada persona, con la puerta de
    # lectura del hogar entero (R7) y la de escritura solo propia (R8, sin cambios: sigue
    # viviendo en `perfiles`). Unidad 010 — ver
    # docs/05-trabajo/010-ver-tu-progreso/especificacion.md del meta-repo. Entrega PARCIAL a
    # propósito: entrenos (R-79) y cumplimiento (R-80) del plano quedan pendientes, sin
    # modelo de datos que los respalde todavía. Sin modelos propios: reutiliza
    # `perfiles.MedicionPeso`, así que no trae migraciones nuevas.
    "progreso",
    # entrenos: lo que la persona ha entrenado, apuntado a mano, y cuánto le suma al objetivo
    # del día. Unidad 011 — ver docs/05-trabajo/011-apuntar-un-entreno/especificacion.md del
    # meta-repo. Dato DE LA PERSONA (no del hogar, mismo criterio que `perfiles.MedicionPeso`):
    # apuntar, corregir y borrar son siempre sobre uno mismo (R10), sin lectura del hogar sobre
    # entrenos ajenos todavía (R-79 llega con Progreso, otra unidad).
    "entrenos",
    # cierres: cerrar el día diciendo si se siguió el plan, con la pregunta al abrir la app
    # para el último día pendiente. Unidad 012 — ver
    # docs/05-trabajo/012-cerrar-el-dia/especificacion.md del meta-repo. Dato DE LA PERSONA (no
    # del hogar, mismo criterio que `entrenos`): cerrar y cambiar un cierre son siempre sobre
    # uno mismo (R12), sin lectura del hogar sobre cierres ajenos. Es el número que dice si el
    # método funciona (R-80 en Progreso, unidad siguiente): esta unidad genera los DATOS, no
    # la gráfica.
    "cierres",
    # despensa: lo que hay en casa, agrupado por categorías; añadir, corregir y quitar
    # productos a mano. Unidad 014 — ver
    # docs/05-trabajo/014-la-despensa/especificacion.md del meta-repo. Es DEL HOGAR (G-43,
    # mismo criterio que `planes`): el segundo modelo que repite el precedente de "el hogar
    # también ESCRIBE" — cualquiera del hogar añade, corrige y quita sin pedir permiso a
    # nadie. Entrega PARCIAL a propósito: descontar al cocinar (R-57) y marcar cantidades
    # aproximadas (R-58) quedan pendientes, sin las piezas de las que dependen (ingredientes
    # de una receta, "marcar una comida como preparada") todavía construidas.
    "despensa",
    # recetas: apuntar los platos que ya sabes hacer, con sus ingredientes y su preparación de
    # corrido. Unidad 021 — ver docs/05-trabajo/021-guardar-tus-recetas/especificacion.md del
    # meta-repo. Es DEL HOGAR (G-43, mismo criterio que despensa/planes) y SIN autor (R-70):
    # cualquiera del hogar apunta, ve, corrige y borra sin pedir permiso a nadie, y no se
    # guarda quién la escribió. Entrega PARCIAL a propósito: R-68 (trocear la preparación en
    # pasos con la IA) y la mitad de R-69 que dice "y permitir ordenarla en pasos más tarde"
    # quedan pendientes — no hay IA en este proyecto todavía. `guardar-tus-recetas` se queda
    # `en obra`, no pasa a `entregada`.
    "recetas",
    # importacion: trae a la app nueva los datos DE VERDAD (despensa, entrenos, recetas y
    # pesadas) de la app Node que sigue en uso, sin identidad ni Strava. Unidad 022 — ver
    # docs/05-trabajo/022-traer-los-datos-de-verdad/especificacion.md del meta-repo. App
    # propia porque `kcalibra` (kcalibra/) no está en INSTALLED_APPS y un management command
    # necesita vivir en una app instalada. Sin modelos propios (no trae migraciones): solo
    # lee la SQLite de Node (de solo lectura, fuera del repo) y escribe a través de las
    # puertas que ya existen (`despensa.logica.anadir_producto`, `entrenos.logica.
    # apuntar_entreno`, `recetas.logica.crear_receta`), nunca con un `create()` a pelo.
    "importacion",
]

AUTH_USER_MODEL = "cuentas.Usuario"
SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # La pide allauth (gestiona detalles de sesión propios, como el "recuérdame").
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Propio de esta unidad (R7, Q-10): resuelve al vuelo la petición de entrada de quien
    # sigue "sola" en cuanto se cumple su hora de plazo. Ver hogares/middleware.py.
    "hogares.middleware.ResolverSolicitudesDelUsuarioMiddleware",
]

AUTHENTICATION_BACKENDS = [
    # El de Django, para el admin y por si algún día hay otra forma de entrar que no pase
    # por allauth.
    "django.contrib.auth.backends.ModelBackend",
    # El de allauth: soporta entrar con correo (en vez de username) y el resto de reglas de
    # esta unidad (bloqueo de intentos, verificación obligatoria...).
    "allauth.account.auth_backends.AuthenticationBackend",
]

ROOT_URLCONF = "kcalibra.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Plantillas compartidas entre apps (la base con Tailwind, HTMX y Alpine ya cargados)
        # viven aquí, no dentro de una app concreta.
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kcalibra.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": variable_obligatoria("DB_NAME"),
        "USER": variable_obligatoria("DB_USER"),
        "PASSWORD": variable_obligatoria("DB_PASSWORD"),
        "HOST": variable_obligatoria("DB_HOST"),
        "PORT": variable_obligatoria("DB_PORT"),
    }
}


# Cuentas y hogares (unidad 003)
# https://docs.allauth.org/en/latest/account/configuration.html

# R12: el registro cerrado/abierto es LA MISMA PALANCA, solo cambiada de posición (G-31). Por
# defecto CERRADO (el valor seguro): hoy la app está en internet y, abierta, cualquiera que
# diera con la dirección podría registrarse y gastar cupo real. Para abrirla de verdad:
# DJANGO_REGISTRO_ABIERTO=True en el entorno.
REGISTRO_ABIERTO = os.environ.get("DJANGO_REGISTRO_ABIERTO", "False") == "True"

ACCOUNT_ADAPTER = "cuentas.adapters.AdaptadorDeCuentas"
ACCOUNT_SIGNUP_FORM_CLASS = "cuentas.forms.FormularioAlta"
# R3 (unidad 008): pedir recuperar la contraseña de un correo que NO existe da la MISMA
# respuesta que pedirlo para uno que sí existe. El formulario de fábrica de allauth
# (`ResetPasswordForm`) decide esto mirando `ACCOUNT_PREVENT_ENUMERATION` — pero esa palanca
# es GLOBAL y aquí está en `False` A PROPÓSITO para otro flujo (R2: avisar si el correo ya
# existe AL REGISTRARSE, justo lo contrario). No se puede usar el mismo ajuste para las dos
# cosas sin romper una de las dos: `FormularioRecuperarContrasena` fija el comportamiento de
# ESTE formulario sin tocar el ajuste global (mismo punto de extensión que
# `ACCOUNT_SIGNUP_FORM_CLASS`, documentado por allauth para justo este caso). Vive en su
# PROPIO módulo, `cuentas/forms_recuperacion.py` — no en `cuentas/forms.py` — porque ese
# fichero se importa DESDE DENTRO de la carga de `allauth.account.forms` (por
# `ACCOUNT_SIGNUP_FORM_CLASS`), y un `import` de `ResetPasswordForm` ahí reventaría con la
# misma trampa de import circular que ya documentó la unidad 003 para `SignupForm` (ver el
# docstring de `cuentas/forms_recuperacion.py`).
ACCOUNT_FORMS = {
    "reset_password": "cuentas.forms_recuperacion.FormularioRecuperarContrasena",
}

# Entrar solo con correo (no hay username: ver cuentas.models.Usuario). El mensaje de error
# no distingue si falla el correo o la contraseña (R4, Q-32) — eso ya lo trae allauth de
# serie con LOGIN_METHODS = {"email"}, aquí solo se traduce el texto (ver AdaptadorDeCuentas).
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_UNIQUE_EMAIL = True
# `Usuario` no tiene ningún campo `username` (ver cuentas/models.py): hay que decírselo a
# allauth explícitamente, si no intenta mirar `Usuario._meta.get_field("username")" al
# montar el formulario de alta y revienta con FieldDoesNotExist.
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

# R13/G-37: verificación de correo OBLIGATORIA. Hasta que se pulsa el enlace, la cuenta existe
# pero no hay forma de entrar (R14): `perform_login` de allauth no llama a `adapter.login()`
# mientras la verificación siga pendiente, así que `request.user` sigue anónimo — es lo que
# hace que cualquier vista con @login_required ya la bloquee, sin código propio.
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
# El enlace vale 24 horas (R15, Q-14) y una sola vez: allauth usa una firma HMAC con el
# instante de envío incrustado (ni guarda el enlace en la base de datos), y una vez que la
# EmailAddress queda verified=True, ese MISMO enlace deja de resolver a nada — no hace falta
# ningún código propio para el "una sola vez".
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1
# Un único clic confirma (R13: "al pulsarlo, entra"), sin un segundo botón de "confirmar"
# en una página intermedia.
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
# Por defecto allauth NO deja entrado a quien acaba de verificar (hay que pedírselo
# explícitamente): sin esto, R13 ("al pulsarlo, entra... sin pedirle iniciar sesión aparte")
# se rompería.
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# R2/R-14: aquí se decide, A PROPÓSITO, ir en contra del valor por defecto de allauth
# (`PREVENT_ENUMERATION = True`, que oculta si un correo ya tiene cuenta para no dar pistas a
# quien esté probando direcciones al azar). Los planos de esta app piden justo lo contrario:
# avisar explícitamente de que ese correo ya tiene cuenta y llevar a quien lo intenta a la
# pantalla de iniciar sesión (R2). Es una decisión de negocio ya tomada, no un descuido.
ACCOUNT_PREVENT_ENUMERATION = False

# R3/G-50: la sesión no caduca por el mero paso del tiempo (ver SESSION_COOKIE_AGE más abajo).
# `SESSION_REMEMBER = True` quita el checkbox de "recuérdame": aquí SIEMPRE se recuerda, no
# hay dos comportamientos distintos según una casilla.
ACCOUNT_SESSION_REMEMBER = True

# R4/Q-12: intentos de acceso fallidos. Se dejan los valores por defecto de allauth (5
# fallos seguidos por correo en una ventana de 5 minutos, más un límite más laxo por IP): ya
# cumplen el contrato ("cierra el acceso desde ahí durante un rato", sin decir cuántos
# intentos ni cuánto rato exactos) y añadir un número propio sin que los planos lo pidan
# sería inventar donde no hace falta.
ACCOUNT_RATE_LIMITS = {
    # H1 de la revisión (2ª ronda): "pedir otro correo" y "corregir la dirección"
    # (cuentas/views.py) no tenían NINGÚN límite propio — allauth solo limita el envío
    # cuando pasa por su propio flujo de login/alta, no cuando se llama a
    # `EmailAddress.send_confirmation()` directamente, como hacen esas dos vistas. Sin este
    # límite, la app sirve de relé para mandar enlaces a cualquier dirección que alguien
    # teclee, una y otra vez. Mismo formato que el límite de accesos fallidos de arriba: por
    # IP Y por correo a la vez.
    "cuentas_correo_pendiente": "5/m/ip,10/h/key",
}

ACCOUNT_EMAIL_SUBJECT_PREFIX = "[KCalibra] "

LOGIN_URL = "account_login"
LOGIN_REDIRECT_URL = "hogares:mi_hogar"
LOGOUT_REDIRECT_URL = "paginas:inicio"

# R3/G-50: "la sesión no caduca por el mero paso del tiempo... sigue dentro después de un
# tiempo largo sin tocar la app". Django expira las sesiones por antigüedad fija
# (SESSION_COOKIE_AGE), no por inactividad, así que la única forma honesta de cumplir esto es
# un plazo deliberadamente enorme (10 años) en vez de "sin límite" (que no existe como opción
# real: siempre hay algún número). Termina solo por logout o cambio de contraseña (más abajo).
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365 * 10
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# Cada petición autenticada alarga la sesión desde "ahora": con esto, alguien que usa la app
# a diario nunca se acerca al límite de arriba (belt-and-suspenders del mismo requisito).
SESSION_SAVE_EVERY_REQUEST = True

# R3/G-52: cambiar la contraseña cierra las DEMÁS sesiones (todas menos la que se está usando
# en ese momento). Esto es Django puro, no allauth: cada sesión guarda un hash derivado de la
# contraseña (`get_session_auth_hash`), y en cuanto la contraseña cambia, cualquier sesión con
# el hash viejo deja de reconocerse como autenticada en su siguiente petición. La sesión ACTUAL
# se mantiene porque el formulario de cambio de contraseña de allauth llama a
# `update_session_auth_hash()` para ella (ver internal/flows/password_change.py). No hace
# falta código propio para ninguna de las dos mitades.

# El correo de verificación y el de recuperar contraseña: por dónde salen (R13, R2; "Cómo" de
# la especificación de la unidad 008). En ESTE portátil, por la consola (así se puede recorrer
# el alta entera sin montar nada). En producción, SMTP de verdad: ADR-004, Resend por SMTP con
# el dominio `kcalibra.app` — decisión ya tomada, sin SDK propio (Django ya habla SMTP de
# serie). Cambiar de backend son estas variables, no código.
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = os.environ.get("DJANGO_DEFAULT_FROM_EMAIL", "no-responder@kcalibra.app")


def _entero_desde_entorno(nombre, por_defecto):
    """
    Lee una variable de entorno numérica. Regla (unidad 009, R1/R2/R10/R11/R12): variable
    AUSENTE o presente pero VACÍA (lo más fácil del mundo al copiar `.env.example` a medias)
    -> el valor por defecto. Si SÍ trae algo, ese valor manda SIEMPRE (R11: no basta con no
    reventar, hay que respetarlo de verdad) — pero solo si tiene sentido: si no es un número
    (R10), o si es un número que no puede serlo (cero o negativo, R12: un timeout así no
    revienta al arrancar, sino DESPUÉS, en plena petición SMTP, con
    `ValueError: Timeout value out of range` — el mismo fallo tardío que R1/R2 cerraron para el
    caso vacío), la app se niega a arrancar nombrando la variable (mismo patrón que
    `variable_obligatoria()`, ahí arriba), nunca un `ValueError` en bruto que no dice cuál de
    las variables había fallado ni cuándo iba a reventar de verdad.
    """
    valor = os.environ.get(nombre, "").strip()
    if not valor:
        return por_defecto
    try:
        numero = int(valor)
    except ValueError:
        raise ImproperlyConfigured(
            f"La variable de entorno '{nombre}' vale {valor!r} y no es un número. "
            "Corrígela en tu .env, o bórrala/déjala vacía para usar el valor por defecto. "
            "Instrucciones completas en AGENTS.md."
        ) from None
    if numero <= 0:
        raise ImproperlyConfigured(
            f"La variable de entorno '{nombre}' vale {valor!r} y tiene que ser mayor que cero. "
            "Corrígela en tu .env, o bórrala/déjala vacía para usar el valor por defecto. "
            "Instrucciones completas en AGENTS.md."
        )
    return numero


# R8: las formas habituales de decir "sí" y de decir "no" en una variable de entorno, sin
# mirar mayúsculas ni espacios de más.
_FORMAS_DE_SI = {"true", "1", "yes", "on", "si", "sí"}
_FORMAS_DE_NO = {"false", "0", "no", "off"}


def _booleano_desde_entorno(nombre, por_defecto):
    """
    Lee una variable de entorno de sí/no. Regla de ausente/vacía igual que
    `_entero_desde_entorno` (unidad 009, R3/R5/R11): -> el valor por defecto. Si SÍ trae algo,
    acepta las formas habituales de `_FORMAS_DE_SI`/`_FORMAS_DE_NO` (R4/R8). Un valor que no
    está en ninguna de las dos listas (un typo como "ture") NUNCA se resuelve como
    "desactivado" — sería colar el mismo fallo del lado inseguro que R3 cerró para la variable
    vacía: la app se niega a arrancar y el mensaje nombra la variable (R9).
    """
    valor_bruto = os.environ.get(nombre, "")
    valor = valor_bruto.strip().lower()
    if not valor:
        return por_defecto
    if valor in _FORMAS_DE_SI:
        return True
    if valor in _FORMAS_DE_NO:
        return False
    raise ImproperlyConfigured(
        f"La variable de entorno '{nombre}' vale {valor_bruto!r} y no se entiende como sí/no. "
        "Usa uno de estos valores: true/1/yes/on/si/sí (activa) o false/0/no/off (desactiva). "
        "Instrucciones completas en AGENTS.md."
    )


# Las variables de conexión SMTP (unidad 008). Con el backend de consola de arriba (el valor
# por defecto en este portátil) `smtp.EmailBackend` ni se importa, así que estas variables no
# se usan para nada — solo entran en juego el día que `DJANGO_EMAIL_BACKEND` apunte al backend
# SMTP real. El repo NUNCA trae credenciales (regla de oro): todo sale del entorno, con
# valores por defecto vacíos o inocuos, nunca con una clave de verdad escrita aquí.
EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "")
EMAIL_PORT = _entero_desde_entorno("DJANGO_EMAIL_PORT", 587)
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = _booleano_desde_entorno("DJANGO_EMAIL_USE_TLS", True)
# La deuda que el ADR-004 deja escrita: sin `EMAIL_TIMEOUT`, Django no pone ningún límite al
# socket SMTP — si el proveedor no contesta, la petición entera (y el hilo que la atiende) se
# queda colgada esperando, indefinidamente. 10 segundos sobra para un envío SMTP normal (y es
# justo el tipo de fallo que R5/R6 tienen que sobrevivir sin dar un 500: ver
# `cuentas/adapters.py`, que captura el `TimeoutError` que esto dispara).
EMAIL_TIMEOUT = _entero_desde_entorno("DJANGO_EMAIL_TIMEOUT", 10)

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Español: la app y sus mensajes (incluidos los de validación de Django/allauth que no se
# traducen a mano) hablan en español.
LANGUAGE_CODE = "es"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Aquí viven los ficheros estáticos que no pertenecen a ninguna app concreta: el CSS que
# genera el binario de Tailwind, y las copias locales de HTMX y Alpine (R3, R5, "Cómo" punto 6).
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
