# Generated by Django 5.2.16 on 2026-08-05 06:09

import cierres.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CierreDeDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        validators=[cierres.models._fecha_no_futura],
                    ),
                ),
                (
                    "respuesta",
                    models.CharField(
                        choices=[
                            ("lo_segui", "Lo seguí"),
                            ("a_medias", "A medias"),
                            ("no_lo_segui", "No lo seguí"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "calorias_comidas",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("nota", models.TextField(blank=True, default="")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cierres_de_dia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="DiaSaltado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dia_saltado_cierre",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuSeguido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cierre",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_seguido",
                        to="cierres.cierrededia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComidaSeguida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "momento_del_dia",
                    models.CharField(
                        choices=[
                            ("desayuno", "Desayuno"),
                            ("comida", "Comida"),
                            ("merienda", "Merienda"),
                            ("cena", "Cena"),
                            ("snack", "Snack / tentempié"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "calorias",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "proteina_g",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "grasa_g",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "carbos_g",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comidas",
                        to="cierres.menuseguido",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="cierrededia",
            constraint=models.UniqueConstraint(
                fields=("usuario", "fecha"), name="un_cierre_por_persona_y_dia"
            ),
        ),
    ]
