# Generated by Django 5.2.16 on 2026-08-03 07:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hogares", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanDeDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hogares.hogar"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes_de_dia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComidaDelPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "momento_del_dia",
                    models.CharField(
                        choices=[
                            ("desayuno", "Desayuno"),
                            ("comida", "Comida"),
                            ("merienda", "Merienda"),
                            ("cena", "Cena"),
                            ("snack", "Snack / tentempié"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "calorias",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "proteina_g",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "grasa_g",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "carbos_g",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comidas",
                        to="planes.plandedia",
                    ),
                ),
            ],
            options={
                "ordering": ["creada_en"],
            },
        ),
        migrations.AddIndex(
            model_name="plandedia",
            index=models.Index(
                fields=["hogar", "fecha"], name="planes_plan_hogar_i_ac8058_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="plandedia",
            constraint=models.UniqueConstraint(
                fields=("usuario", "fecha"), name="un_plan_por_persona_y_dia"
            ),
        ),
    ]
