# Generated by Django 5.2.16 on 2026-08-10 14:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hogares", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "raciones",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("comidas", models.JSONField(blank=True, default=list)),
                ("preparacion", models.TextField(blank=True, default="")),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hogares.hogar"
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="IngredienteDeReceta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("ud", "Unidades"),
                            ("g", "Gramos"),
                            ("kg", "Kilos"),
                            ("ml", "Mililitros"),
                            ("l", "Litros"),
                            ("paquete", "Paquetes"),
                            ("lata", "Latas"),
                            ("bote", "Botes"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredientes",
                        to="recetas.receta",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
