# Generated by Django 5.2.16 on 2026-08-02 14:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import perfiles.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicionPeso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "peso_kg",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1"))
                        ],
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mediciones_peso",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("hombre", "Hombre"), ("mujer", "Mujer")],
                        max_length=10,
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(validators=[perfiles.models._fecha_no_futura]),
                ),
                (
                    "altura_cm",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "actividad",
                    models.CharField(
                        choices=[
                            ("sedentario", "Sedentario/a (poco o ningún ejercicio)"),
                            ("ligero", "Actividad ligera (ejercicio 1-3 días/semana)"),
                            (
                                "moderado",
                                "Actividad moderada (ejercicio 3-5 días/semana)",
                            ),
                            ("activo", "Activo/a (ejercicio 6-7 días/semana)"),
                            (
                                "muy_activo",
                                "Muy activo/a (ejercicio intenso a diario, o trabajo físico)",
                            ),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(
                        choices=[
                            ("mantener", "Mantener mi peso"),
                            ("perder_grasa", "Perder grasa"),
                            ("ganar_musculo", "Ganar músculo"),
                            ("rendimiento", "Rendimiento deportivo"),
                            (
                                "recomposicion_corporal",
                                "Recomposición corporal (ganar músculo y perder grasa a la vez)",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                ("ajuste_pct", models.SmallIntegerField()),
                ("dieta", models.CharField(blank=True, default="", max_length=100)),
                ("alergias", models.TextField(blank=True, default="")),
                ("intolerancias", models.TextField(blank=True, default="")),
                ("no_le_gusta", models.TextField(blank=True, default="")),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
