# Generated by Django 5.2.16 on 2026-08-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfiles", "0002_grasa_cintura_y_una_por_dia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="actividad",
            field=models.CharField(
                choices=[
                    (
                        "sedentario",
                        "Sedentario/a (trabajo de oficina, te mueves poco en tu día a día)",
                    ),
                    (
                        "ligero",
                        "Algo activo/a (tu día a día tiene cierto movimiento: caminas, subes escaleras)",
                    ),
                    (
                        "moderado",
                        "Activo/a (tu día a día tiene bastante movimiento: de pie, caminando, tareas físicas)",
                    ),
                    (
                        "activo",
                        "Muy activo/a (tu día a día exige esfuerzo físico constante)",
                    ),
                    (
                        "muy_activo",
                        "Extremadamente activo/a (trabajo físico intenso o mucho movimiento todo el día)",
                    ),
                ],
                max_length=15,
            ),
        ),
    ]
