# Generated by Django 5.2.16 on 2026-08-05 11:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hogares", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoDespensa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "nombre_normalizado",
                    models.CharField(db_index=True, editable=False, max_length=150),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("ud", "Unidades"),
                            ("g", "Gramos"),
                            ("kg", "Kilos"),
                            ("ml", "Mililitros"),
                            ("l", "Litros"),
                            ("paquete", "Paquetes"),
                            ("lata", "Latas"),
                            ("bote", "Botes"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("verdura", "Verdura"),
                            ("fruta", "Fruta"),
                            ("carne", "Carne"),
                            ("pescado", "Pescado"),
                            ("huevos", "Huevos"),
                            ("lacteo", "Lácteo"),
                            ("cereal_pan", "Cereales y pan"),
                            ("legumbre", "Legumbres"),
                            ("fruto_seco", "Frutos secos"),
                            ("aceite_grasa", "Aceites y grasas"),
                            ("bebida", "Bebidas"),
                            ("dulce_snack", "Dulces y snacks"),
                            ("condimento", "Condimentos"),
                            ("congelado", "Congelados"),
                            ("otro", "Otro"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "en_casa_desde",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hogares.hogar"
                    ),
                ),
            ],
            options={
                "ordering": ["categoria", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["hogar", "categoria"],
                        name="despensa_pr_hogar_i_cdf9f0_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hogar", "nombre_normalizado", "unidad"),
                        name="una_linea_por_hogar_producto_y_unidad",
                    )
                ],
            },
        ),
    ]
