# Generated by Django 5.2.16 on 2026-08-04 16:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import entrenos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entreno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        validators=[entrenos.models._fecha_no_futura],
                    ),
                ),
                (
                    "deporte",
                    models.CharField(
                        choices=[
                            ("correr", "Correr"),
                            ("bici", "Bici"),
                            ("nadar", "Nadar"),
                            ("fuerza", "Fuerza"),
                            ("crossfit", "CrossFit"),
                            ("hyrox", "Hyrox"),
                            ("otro", "Otro"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "intensidad",
                    models.CharField(
                        choices=[
                            ("suave", "Suave"),
                            ("media", "Media"),
                            ("fuerte", "Fuerte"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "minutos",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "calorias",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("calorias_manuales", models.BooleanField(default=False)),
                (
                    "origen",
                    models.CharField(
                        choices=[("mano", "A mano"), ("strava", "Strava")],
                        default="mano",
                        max_length=10,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrenos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "fecha"],
                        name="entrenos_en_usuario_fa18be_idx",
                    )
                ],
            },
        ),
    ]
